apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-upf2
  labels:
    app: open5gs
    nf: upf2
    name: upf2
spec:
  selector:
    matchLabels:
      app: open5gs
      nf: upf2
      name: upf2
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs
        nf: upf2
        name: upf2
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "n3network", "interface": "n3", "ips": [ "10.10.3.2/24" ] },
          { "name": "n4network", "interface": "n4", "ips": [ "10.10.4.2/24" ] }
          ]'
    spec:
      nodeSelector:
        kubernetes.io/hostname: cn231
      containers:
      - name: upf
        image: ghcr.io/niloysh/open5gs:v2.6.4-aio
        imagePullPolicy: IfNotPresent
        command: [ "/open5gs/config/wrapper.sh" ]
        volumeMounts:
        - mountPath: /open5gs/config/
          name: upf-volume
        ports:
        - containerPort: 8805
          name: n4
          protocol: UDP
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        securityContext:
          privileged: true
      restartPolicy: Always
      volumes:
      - name: upf-volume
        configMap:
          name: upf2-configmap
          items:
          - key: upfcfg.yaml
            path: upfcfg.yaml
          - key: wrapper.sh
            path: wrapper.sh
            mode: 0777
