apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-nssf
  labels:
    app: open5gs
    nf: nssf
spec:
  selector:
    matchLabels:
      app: open5gs
      nf: nssf
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs
        nf: nssf
    spec:
      initContainers:
      - name: wait-udr
        image: busybox:1.32.0
        env:
        - name: DEPENDENCIES
          value: udr-nudr:80
        command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the UDR; sleep 2; done;"]
      containers:
      - image: ghcr.io/niloysh/open5gs:v2.6.4-aio
        imagePullPolicy: IfNotPresent
        name: nssf
        ports:
        - containerPort: 80
        command: ["./open5gs-nssfd"]
        args: ["-c", "/open5gs/config/nssfcfg.yaml"]   
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /open5gs/config/
          name: nssf-volume
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: nssf-volume
        projected:
          sources:
          - configMap:
              name: nssf-configmap
